package exep;

public class Main {
     
     public static void main(String[] args) {
          
         try{ int a=19,b=0;}
              catch(Exception e)
              {
          System.out.println("erreur");}
          System.out.println("continue");
     }
     
}